backend:
  name: github
  repo: ilajosmanov/nonlbs
  branch: main
media_folder: static/images
public_folder: /static
media_library:
  name: uploadcare
  config:
    publicKey: 378aa027f5500b010321

collections:
  - name: Proudcts
    label: Products
    folder: content/catalog
    create: true
    identifier_field: title
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "price", label: "Price", widget: "string" }
      - { name: "size", label: "Size", widget: "string" }
      - { name: "width", label: "Width", widget: "string" }
      - { name: "length", label: "Length", widget: "string" }
      - { name: "shoulders", label: "Shoulders", widget: "string" }
      - { name: "sleeve", label: "Sleeve", widget: "string" }
      - { name: "description", label: "Description", widget: "markdown" }
      - name: cover
        label: Cover Image
        widget: image
        media_library:
          config:
            multiple: true
            previewStep: false
