backend:
  name: github
  repo: ilajosmanov/nonlbs
  branch: main
  site_url: https://nonlbs.com
media_folder: /static
public_folder: ../../static

collections:
  - name: Proudcts
    label: Products
    folder: content/catalog
    create: true
    identifier_field: title
    editor:
      preview: false
    fields:
      - { name: "templateKey", label: "Template Key", widget: "hidden", default: "product-page" }
      - { name: "title", label: "Title", widget: "string" }
      - { name: "price", label: "Price", widget: "string" }
      - { name: "size", label: "Size", widget: "string" }
      - { name: "width", label: "Width", widget: "string", required: false, default: "0" }
      - { name: "length", label: "Length", widget: "string", required: false, default: "0" }
      - { name: "shoulders", label: "Shoulders", widget: "string", required: false, default: "0" }
      - { name: "sleeve", label: "Sleeve", widget: "string", required: false, default: "0" }
      - { name: "waist", label: "Waist", widget: "string", required: false, default: "0" }
      - { name: "rise", label: "Rise", widget: "string", required: false, default: "0" }
      - { name: "description", label: "Description", widget: "markdown" }
      - label: "Gallery"
        name: "images"
        widget: "list"
        summary: '{{fields.image}}'
        fields:
          - {label: Image, name: "image1", widget: image}
          - {label: Image, name: "image2", widget: image, required: false}
          - {label: Image, name: "image3", widget: image, required: false}
          - {label: Image, name: "image4", widget: image, required: false}
